# syntax=docker/dockerfile:1.3
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV HTTP_PROXY=$HTTP_PROXY \
    HTTPS_PROXY=$HTTPS_PROXY

RUN apt-get update -y && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  python3 \
  tar \
  zip \
  unzip \
  xz-utils \
  g++-10 \
  gcc-10 \
  zlib1g-dev \
  libstdc++-10-dev \
  pkg-config \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

USER cnb