# syntax=docker/dockerfile:1.3
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install necessary packages
RUN apt-get update && apt-get install -y \
    # Dependencies for building apps
    cmake \
    ninja-build \
    # Clean up
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]
